//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thongtinlietsi
    {
        public int Id { get; set; }
        public string Hoten { get; set; }
        public string Quequan { get; set; }
        public string Truquan { get; set; }
        public string Ngaynhapngu { get; set; }
        public string Donvi { get; set; }
        public string Capbac { get; set; }
        public string Chucvu { get; set; }
        public string Ngayhisinh { get; set; }
        public string Truonghophisinh { get; set; }
        public string Noimaitang { get; set; }
        public string Thannhan { get; set; }
        public string Tennghiatrang { get; set; }
        public string Somo { get; set; }
        public string Namsinh { get; set; }
    }
}
